# Generated by Django 5.1.3 on 2024-11-08 11:06

import interior.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='design_image',
            field=models.ImageField(upload_to='interior/design', validators=[interior.models.validate_image], verbose_name='Фото'),
        ),
    ]
