# Generated by Django 5.1.3 on 2024-11-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FIO',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
