# Generated by Django 5.1.3 on 2024-11-08 12:32

import django.db.models.deletion
import interior.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_alter_request_design_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior.category'),
        ),
        migrations.AlterField(
            model_name='request',
            name='design_image',
            field=models.ImageField(upload_to='interior/design', validators=[interior.models.Request.validate_image], verbose_name='Фото'),
        ),
    ]
