# Generated by Django 5.1.3 on 2024-11-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_alter_request_category_alter_request_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
