# Generated by Django 5.1.3 on 2024-11-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_category_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
    ]
