# Generated by Django 5.1.3 on 2024-11-09 03:49

import django.db.models.deletion
import interior.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0003_request_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='final_image',
            field=models.ImageField(blank=True, null=True, upload_to='interior/design', validators=[interior.models.Request.validate_image], verbose_name='Финальное фото'),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interior.category'),
        ),
    ]
